### ISSUE TITLE
Shorter way to take over a user

### ISSUE THREAD

**Issue by wanze** [studer-raimann/UserTakeOver#10]
Currently it's only possible to take over a user by navigating to 

`Administration > Users > Search User > View Details > Click "TakeOver" button`

Some ideas:
- Add a input field to the mainmenu where one can enter a username directly
- Display a input field to enter the username with a hidden shortcut, e.g. by typing "ut"

**Comment by mhilbert** [comment]
It should be possible to switch off this new option via the plugin configuration.

In our opinion, the possibility of taking over a user is too obvious for all administrators when there's this input field "Benutzerübernahme" in the top bar navigation.

**Comment by chfsx** [comment]
No configuration planed since we want the feature to behave exactly like this.
