### ISSUE TITLE
ilias 5.3.* compatibility

### ISSUE THREAD

**Issue by kinimodmeyer** [studer-raimann/UserTakeOver#19]
hallo zusammen, wann wir das plugin auf den 5.3 zweig gehoben.
kann man ohne probleme die $ilias_max_version = '5.2.999'; auf 5.3.999 ändern?

**Comment by chfsx** [comment]
Hallo Dominik. Wir veröffentlichen alle unsere Plugins immer open source, allerdings können wir nicht generell die Kompatibilität zu neuen ILIAS-Versionen garantieren. Die Plugins werden jeweils für Hosting-Kunden bei uns dann bei Upgrades gepflegt. Du kannst gerne versuchen das Plugin so bei dir mit 5.3 zu nutzen, über eine Rückmeldung würden wir uns sehr freuen. Dieses Plugin wird unsererseits voraussichtlich erst im neuen Jahr für 5.3 aufbereitet, wenn du und aber bereits ein Feedback geben kannst, ob es läuft, können wir ev. bereits früher den neuen Release machen. Vielen Dank!
