### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by otruffer** [studer-raimann/UserTakeOver#8]
Some thoughts:

On UserTakeOver / classes / class.usrtoGUI.php:71 
$ilObjUser = new ilObjUser($_SESSION[self::ACCOUNT_ID]);

Seems to be unused.

Is there a session abstraction in ILIAS that could be used instead of accessing the superglobal $_SESSION?
Is it worth building a model class? (separating access control and actual takeover)

Cheers
Oskar

**Comment by chfsx** [comment]
has been refactored
